world: world
message:
  top: '&6&l%top%&6: &6%player%: &7%points%'
  already_event: '&cIl y a deja un event en cours !'
  config_reloaded: '&aConfiguration Réinitialisée'
  config_updated: '&aConfiguration mise à jour'
  chest_added: "&aLe coffre a été ajouté avec sucés"
  inv_empty: "&cCe coffre est vide !"
  error_chest: "&cCe block n'est pas un coffre !"
  error_inv: "&cCe nom est deja pris"
database:
  host: localhost
  port: '3306'
  database: Test
  user: admin
  password: password
  table: SpartaCube
times:
  chest_delete: 10
  game: 15
  wait: 15
broadcast:
  times:
    - 5
    - 4
    - 3
    - 2
    - 1
  chest_opened: '&aUn coffre a été ouvert par &6&l%player%'
  event_stop_in: '&aL''event se termine dans %time%'
  event_starts_in: '&aL''event commence dans %time%'
  event_wait: '&aPréparation de l''Event TreasureMap'
  event_start: '&aDébut de l''Event TreasureMap'
  event_finished: "&cFin de l'Event: &6%opened% &acoffres ouverts"
inventories:

locations:
  bas:
    x: 17
    y: 68
    z: 15
  mid:
    x: 17
    y: 69
    z: 15
  top:
    x: 17
    y: 70
    z: 15
  etop:
    x: 17
    y: 71
    z: 15